using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Goobstation.Client.Speech;

[Virtual]
[GenerateTypedNameReferences]
public partial class TelepathyWindow : BaseWindow
{
    public TelepathyWindow()
    {
        RobustXamlLoader.Load(this);
    }
    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }
}
